server:
  port: ${PORT:8081}

spring:
  application:
    name: spring-boot-exchange-rate
  cloud:
    config:
      name: spring-boot-exchange-rate
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=demodb;encrypt=false
    password: yourStrong(!)Password
    username: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
