spring:
  datasource:
    url: jdbc:postgresql://204.216.105.102:5432/postgres
    username: postgres
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  configuration:
    description: this is a dev description

logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG
    org.springframework.vault.authentication: DEBUG